### ISSUE TITLE
should have a demo of project.

### ISSUE THREAD

**Issue by praveeno** [thoughtram/classroom-app#11]
hello guys,
I recently found this and what to see how this `classroom-app` look & feel, can we add a demo link in readme, so any visitor can feel your app.
let me know if guys open for PR and issues.

**Comment by 0x-r4bbit** [comment]
Hey @praveeno 

This application is up online at http://classroom.thoughtram.io and is only accessible to students that joined our workshops, which makes adding a demo link rather unlikely.

Thanks for your request ho!
